environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
      CONDA_NPY: "19"

    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      CONDA_NPY: "19"
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "34"
      CONDA_NPY: "19"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "34"
      CONDA_NPY: "19"
      ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels omnia
  - conda update -yq --all
  - conda install -yq conda-build jinja2

build: false

test_script:
  - "%CMD_IN_ENV% conda build --quiet devtools\\conda-recipe"
